image: registry.gitlab.tech.orange/qalabs/samples/playwright_build_docker:main

stages:
  - test

test:
   stage : test
   allow_failure: true
   artifacts:
     when: always
     paths:
       - playwright-report/
       - test-results/
     name: "$CI_JOB_STARTED_AT"
   script:
     - cp -rf $PWD/tests /app
     - cp -f $PWD/playwright.config.js /app
     - cd /app
     - npx playwright test
   after_script:
     - mv /app/playwright-report .
     - mv /app/test-results .

